# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: Greeter
description: GMX-Positions
field_selection: 
  transaction_fields:
    - "hash"
    - "transactionIndex"
#Global contract definitions that must contain all definitions except
#addresses. Now you can share a single handler/abi/event definitions
#for contracts across multiple chains
contracts:
  - name: GMX_EventEmitter
    abi_file_path: ./abis/EventEmitter.json
    handler: ./src/EventHandlers.ts
    events:
      - event: EventLog1
      - event: EventLog2
networks:
  - id: 42161
    start_block: 244150002
    contracts:
      - name: GMX_EventEmitter #A reference to the global contract definition
        address: 0xC8ee91A54287DB53897056e12D9819156D3822Fb